# Install using stack on Portainer
version: '3.9'

networks:
  ginproject:
    external: true

services:
  cloudflaretunnel:
    container_name: cloudflare-tunnel-1
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=$TUNNEL_TOKEN
    command: tunnel --no-autoupdate run
    networks:
      - ginproject